version: "3.3"
services:
  kafka:
    image: krisgeus/docker-kafka
    environment:
      LOG_RETENTION_HOURS: 1
      AUTO_CREATE_TOPICS: "true"
      ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://localhost:9093
      LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093
      SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      INTER_BROKER: INTERNAL
    ports:
      - 9092:9092
      - 2181:2181
  divolte:
    build:
      context: "./divolte"
    environment:
      DIVOLTE_KAFKA_BROKER_LIST: kafka:9092
      DIVOLTE_JAVASCRIPT_AUTO_PAGE_VIEW_EVENT: "false"
    ports:
      - 8290:8290
    depends_on:
      - kafka
  streamsets:
    build:
      context: "./streamsets"
      args:
        SDC_LIBS: streamsets-datacollector-apache-kafka_2_0-lib
    ports:
      - 18630:18630
    volumes:
      - ./streamsets/data:/data
      - ./streamsets/credentials:/opt/credentials
    depends_on:
      - kafka
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
#    volumes:
#      - ./clickhouse-data:/var/lib/clickhouse
    depends_on:
      - kafka
