FROM divolte/divolte-collector

COPY ./conf/divolte-collector.conf /opt/divolte/divolte-collector/conf/divolte-collector.conf
COPY ./mappings/schema.avsc /opt/divolte/divolte-collector/mappings/schema.avsc
COPY ./mappings/schema-mapping.groovy /opt/divolte/divolte-collector/mappings/schema-mapping.groovy
